version: "3"
services:
    csv2db:
        image: node
        depends_on:
            - "mongo-server"
        links:
            - "mongo-server"
        volumes:
            - ./csv2db:/work
            - ./sh:/sh
        working_dir:    /work
        command: ["/sh/wait-for-it.sh", "mongo-server:27017", "--", "node", "csv2json.js", "data/lessons.csv"]
    mongo-server:
        image:  mongo
        volumes:
            - ./database:/data/db
        expose: 
            - "27017"
    lessonsserver:
        image: node
        depends_on:
            - "mongo-server"
        links:
            - "mongo-server"
        volumes:
            - ./lessonserver:/work
            - ./sh:/sh
        working_dir:    /work
        command: ["/sh/wait-for-it.sh", "mongo-server:27017", "--", "node", "app.js"]
        ports:
            - "3000:3000"
