version: "3"
services:
    nginx-server:
        image:  nginx
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
            - ./:/usr/share/nginx
        ports: 
            - "6060:80"
