version: "3"
services:
    mongo-server:
        image:  mongo
        volumes:
            - ../database:/data/db
        expose: 
            - "27017"
    lessonsserver:
        image: node
        depends_on:
            - "mongo-server"
        links:
            - "mongo-server"
        volumes:
            - ./:/work
            - ../sh:/sh
        working_dir:    /work
        command: ["/sh/wait-for-it.sh", "mongo-server:27017", "--", "node", "app.js"]
        ports:
            - "3001:3001"
